openapi: 3.0.0
info:
  version: 1.0.0
  title: SOPT API docs
  description: SOPT SERVER SEMINAR
  license:
    name: Jang
servers:
  - url: http://localhost:8080/ #자신의 포트번호

#Paths api 경로 지정
paths: {}
