name: Build and Push Q&A Board service

on:
  push:
    paths:
        - 'Q&A_board_service/**'
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                java-version: '17'    
                distribution: 'temurin'
            - name: Gradle Caching
              uses: actions/cache@v3
              with:
                path: |
                    ~/.gradle/caches
                    ~/.gradle/wrapper
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                restore-keys: |
                    ${{ runner.os }}-gradle-
            - name: Grant execute permission for gradlew
              run: chmod +x ./gradlew
              shell: bash
                      
            - name: Build with Gradle
              run: ./gradlew build
              shell: bash            
            
             
            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to Dockerhub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                context: ./Q&A_board_service
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/chatbot:${{github.run_number}}
                platforms: linux/amd64,linux/arm64
                cache-from: type=gha
                cache-to: type=gha, mode=max