name: Build and Push Q&A Board service

on:
  push:
    paths:
        - 'QA_board_service/**'
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{github.run_number}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'    
          distribution: 'temurin'
    
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
              ${{ runner.os }}-gradle-
                
      - name: build project 
        run: |
          cd QA_board_service
          chmod +x ./gradlew
          ./gradlew build
        shell: bash

      - name: build openapi3
        run: |
          cd QA_board_service
          chmod +x ./gradlew
          ./gradlew openapi3
        shell: bash
      
      - name: Copy file
        run: |
          ls
          cp QA_board_service/build/api-spec/openapi3.json /Swagger/docs/QA-board-service.json
        shell: bash

      - name: Commit change
        env: 
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git config --global user.email "matkimchi_@naver.com"
          git config --global user.name "kyounghoonJang"
          git add /Swagger/docs/QA-board-service.json
          git commit -m "Update QA-board-service.json"
          git push origin main
      
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./QA_board_service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/probono_qa_board:${{github.run_number}}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha, mode=max
  push:
    name: Push Manifests
    needs: build
    runs-on: ubuntu-latest
    env:
      TAG: ${{needs.build.outputs.TAG}}
    steps:
      - name: Clone Repository B
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'main'
          owner: 'probono-24PF012'
          repository: 'ruddy-Infra'

      
      - name: Access cloned repository content
        run: |
          cd ruddy-Infra
          cd k8s
          sed -i "s|matkimchi/probono_qa_board:[^ ]|matkimchi/probono_qa_board:${{env.TAG}}|" "application.yml"
          git config --global user.email "matkimchi_@naver.com"
          git config --global user.name "kyounghoonJang"
          git add application.yml
          git commit -m "Update application.yml"
      
      - name: Push to Reposiroty Ruddy Infra
        run: |
          cd ruddy-Infra
          git remote set-url origin https://x-access-token:${{ secrets.INFRA_PAT }}@github.com/probono-24PF012/ruddy-Infra.git
          git push 
      
      
          
