name: Build and Push Q&A Board service

on:
  push:
    paths:
        - 'QA_board_service/**'
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{github.run_number}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'    
          distribution: 'temurin'
    
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
              ${{ runner.os }}-gradle-
                
      - name: build project 
        run: |
          cd QA_board_service
          chmod +x ./gradlew
          ./gradlew build
        shell: bash
      
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./QA_board_service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/probono_qa_board:${{github.run_number}}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha, mode=max
  push:
    name: Push Manifests
    needs: build
    runs-on: ubuntu-latest
    env:
      TAG: ${{needs.build.outputs.TAG}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: probono-24PF012/ruddy-Infra
          token: ${{ secrets.INFRA_PAT }}
          path: k8s
      - name: List files for debugging
        run: ls -R
      - name: Change manifest
        run: sed -i "s|matkimchi/probono_qa_board:[^ ]|matkimchi/probono_qa_board:${{env.TAG}}|" "k8s/k8s/application.yml"
          
      - name: Commit files
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -a -m "Add changes"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.INFRA_PAT }}
          branch: main
      
      
          